# Generated by Django 2.2.1 on 2019-08-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default_avatar.jpg', upload_to='profile_pics'),
        ),
    ]
