# Generated by Django 2.2.1 on 2019-09-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='follows',
        ),
    ]
