# Generated by Django 2.2.1 on 2019-06-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
