# Generated by Django 2.2.1 on 2019-07-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_remove_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
