# Generated by Django 2.2.1 on 2019-09-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20190828_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
